#This is for development only.

# Use root/example as user/password credentials

version: "3.1"

services:
    # Mongo Replica set

    # Primary Node
    mongo:
        image: mongo:6
        container_name: mongo
        restart: on-failure
        command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27017"]
        volumes:
            - mongo:/data/db
        ports:
            - 27017:27017
        healthcheck:
            test: test $$(echo "rs.initiate({_id:'rs0',members:[{_id:0,host:\"mongo:27017\"}]}).ok || rs.status().ok" | mongosh --port 27017 --quiet) -eq 1
            interval: 10s
            start_period: 30s

volumes:
    mongo:
