name: PR-CHECKS-PIPELINE

on:
    pull_request:
        types: ["opened", "reopened", "ready_for_review", "synchronize"]
    workflow_dispatch:

jobs:
    test:
        permissions:
            checks: write
            deployments: write
            packages: write
            pull-requests: write
            statuses: write
            repository-projects: write
            actions: write
            contents: write
            id-token: write
        name: Test
        runs-on: ubuntu-latest
        timeout-minutes: 20
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: "18"
                  registry-url: https://npm.pkg.github.com
                  cache: "npm"
                  scope: "@eftours"
            - name: Install dependencies
              run: npm ci
            - name: Generate Types
              run: npm run generate
            - name: Typecheck
              run: npm run typecheck
            - name: Test
              run: npm run test
